# otel demo trimmed down - it ships its own observability tools, we already run our own

opentelemetry-collector:
  config:
    exporters:
      otlphttp/prometheus:
        endpoint: http://monitoring-kube-prometheus-prometheus.monitoring:9090/api/v1/otlp

opensearch:
  enabled: false
jaeger:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false

components:
  frontend-proxy:
    service:
      type: NodePort
      nodePort: 30080
